languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- test/
- vendor/
- doc/
- examples/