languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
# exclude_paths:
# - "foo/bar.rb"
engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
